# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_system"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "(mostly)POSIX system routine interface"

executable = [
{  name="demo_system_access",       source-dir="demo",       main="system_access.f90"       },
{  name="demo_system_chdir",        source-dir="demo",        main="system_chdir.f90"        },
{  name="demo_system_chmod",        source-dir="demo",        main="system_chmod.f90"        },
{  name="demo_system_chown",        source-dir="demo",        main="system_chown.f90"        },
{  name="demo_system_clearenv",     source-dir="demo",     main="system_clearenv.f90"     },
{  name="demo_system_closedir",     source-dir="demo",     main="system_closedir.f90"     },
{  name="demo_system_cpu_time",     source-dir="demo",     main="system_cpu_time.f90"     },
{  name="demo_system_errno",        source-dir="demo",        main="system_errno.f90"        },
{  name="demo_system_getcwd",       source-dir="demo",       main="system_getcwd.f90"       },
{  name="demo_system_getegid",      source-dir="demo",      main="system_getegid.f90"      },
{  name="demo_system_getenv",       source-dir="demo",       main="system_getenv.f90"       },
{  name="demo_system_geteuid",      source-dir="demo",      main="system_geteuid.f90"      },
{  name="demo_system_getgid",       source-dir="demo",       main="system_getgid.f90"       },
{  name="demo_system_getgrgid",     source-dir="demo",     main="system_getgrgid.f90"     },
{  name="demo_system_gethostname",  source-dir="demo",  main="system_gethostname.f90"  },
{  name="demo_system_getlogin",     source-dir="demo",     main="system_getlogin.f90"     },
{  name="demo_system_getpid",       source-dir="demo",       main="system_getpid.f90"       },
{  name="demo_system_getppid",      source-dir="demo",      main="system_getppid.f90"      },
{  name="demo_system_getpwuid",     source-dir="demo",     main="system_getpwuid.f90"     },
{  name="demo_system_getsid",       source-dir="demo",       main="system_getsid.f90"       },
{  name="demo_system_getuid",       source-dir="demo",       main="system_getuid.f90"       },
{  name="demo_system_getumask",     source-dir="demo",     main="system_getumask.f90"     },
{  name="demo_system_initenv",      source-dir="demo",      main="system_initenv.f90"      },
{  name="demo_system_isblk",        source-dir="demo",        main="system_isblk.f90"        },
{  name="demo_system_ischr",        source-dir="demo",        main="system_ischr.f90"        },
{  name="demo_system_isdir",        source-dir="demo",        main="system_isdir.f90"        },
{  name="demo_system_isfifo",       source-dir="demo",       main="system_isfifo.f90"       },
{  name="demo_system_islnk",        source-dir="demo",        main="system_islnk.f90"        },
{  name="demo_system_isreg",        source-dir="demo",        main="system_isreg.f90"        },
{  name="demo_system_issock",       source-dir="demo",       main="system_issock.f90"       },
{  name="demo_system_kill",         source-dir="demo",         main="system_kill.f90"         },
{  name="demo_system_link",         source-dir="demo",         main="system_link.f90"         },
{  name="demo_system_mkdir",        source-dir="demo",        main="system_mkdir.f90"        },
{  name="demo_system_mkfifo",       source-dir="demo",       main="system_mkfifo.f90"       },
{  name="demo_system_opendir",      source-dir="demo",      main="system_opendir.f90"      },
{  name="demo_system_perm",         source-dir="demo",         main="system_perm.f90"         },
{  name="demo_system_perror",       source-dir="demo",       main="system_perror.f90"       },
{  name="demo_system_putenv",       source-dir="demo",       main="system_putenv.f90"       },
{  name="demo_system_rand",         source-dir="demo",         main="system_rand.f90"         },
{  name="demo_system_readdir",      source-dir="demo",      main="system_readdir.f90"      },
{  name="demo_system_readenv",      source-dir="demo",      main="system_readenv.f90"      },
{  name="demo_system_realpath",     source-dir="demo",     main="system_realpath.f90"     },
{  name="demo_system_remove",       source-dir="demo",       main="system_remove.f90"       },
{  name="demo_system_rename",       source-dir="demo",       main="system_rename.f90"       },
{  name="demo_system_rewinddir",    source-dir="demo",    main="system_rewinddir.f90"    },
{  name="demo_system_rmdir",        source-dir="demo",        main="system_rmdir.f90"        },
{  name="demo_system_setsid",       source-dir="demo",       main="system_setsid.f90"       },
{  name="demo_system_setumask",     source-dir="demo",     main="system_setumask.f90"     },
{  name="demo_system_srand",        source-dir="demo",        main="system_srand.f90"        },
{  name="demo_system_uname",        source-dir="demo",        main="system_uname.f90"        },
{  name="demo_system_unlink",       source-dir="demo",       main="system_unlink.f90"       },
{  name="demo_system_unsetenv",     source-dir="demo",     main="system_unsetenv.f90"     },
{  name="demo_system_utime",        source-dir="demo",        main="system_utime.f90"        } 
]
# {  name="demo_system_stat",         source-dir="demo",    main="system_stat.f90"         },
# {  name="demo_system_stat_print",   source-dir="demo",    main="system_stat_print.f90"   },

[build]
auto-executables = false

[library]
source-dir="src"

[dev-dependencies]
   M_msg          = { git = "https://github.com/urbanjost/M_msg.git" }
   M_time         = { git = "https://github.com/urbanjost/M_time.git" }
   M_process      = { git = "https://github.com/urbanjost/M_process.git" }
